export const CURRENCY_STORE = 'CURRENCY_STORE';
export const COUNTRY_STORE = 'COUNTRY_STORE';
export const SELECTED_COUNTRY = 'SELECTED_COUNTRY';
export const SELECTED_CURRENCY = 'SELECTED_CURRENCY';
